/** Dark navy sidebar with purple active states — matches Him Journey Tours design */
const DARK_NAVY = {
  brandGradient: 'from-orange-500 to-orange-600',
  brandShadow: 'shadow-orange-500/40',
  brandGlow: 'bg-orange-400/20',
  titleOrange: 'text-white',
  titleGradient: 'text-white',
  indicator: 'bg-[#5D5FEF]',
  iconActive: 'text-white',
  iconBoxActive: 'bg-transparent',
  iconInactive: 'text-slate-400 group-hover:text-slate-200',
  itemActive: 'bg-[#5D5FEF] text-white shadow-md shadow-[#5D5FEF]/30',
  groupActive: 'text-white bg-white/[0.06]',
  searchFocus: 'focus:ring-[#5D5FEF]/30 focus:border-[#5D5FEF]/40',
  searchIconFocus: 'group-focus-within:text-slate-400',
  avatarGradient: 'from-orange-500 to-orange-600',
  badge: 'bg-[#5D5FEF]/25 text-violet-200',
};

export const SIDEBAR_ACCENTS = {
  brand: {
    ...DARK_NAVY,
    headerBg: 'from-transparent to-transparent',
    headerBorder: 'border-white/10',
    titleGradient: 'text-white',
    subtitleBg: 'bg-white/10',
    subtitleText: 'text-slate-400',
    subtitleBorder: 'border-white/10',
    overlay: 'from-transparent to-transparent',
  },
  violet: {
    ...DARK_NAVY,
    itemActive: 'bg-[#5D5FEF] text-white shadow-md shadow-[#5D5FEF]/30',
    headerBg: 'from-transparent to-transparent',
    headerBorder: 'border-white/10',
    titleGradient: 'text-white',
    subtitleBg: 'bg-violet-500/15',
    subtitleText: 'text-violet-300',
    subtitleBorder: 'border-violet-500/25',
    overlay: 'from-transparent to-transparent',
  },
  teal: {
    ...DARK_NAVY,
    headerBg: 'from-transparent to-transparent',
    headerBorder: 'border-white/10',
    titleGradient: 'text-white',
    subtitleBg: 'bg-teal-500/15',
    subtitleText: 'text-teal-300',
    subtitleBorder: 'border-teal-500/25',
    overlay: 'from-transparent to-transparent',
  },
  sky: {
    ...DARK_NAVY,
    headerBg: 'from-transparent to-transparent',
    headerBorder: 'border-white/10',
    titleGradient: 'text-white',
    subtitleBg: 'bg-sky-500/15',
    subtitleText: 'text-sky-300',
    subtitleBorder: 'border-sky-500/25',
    overlay: 'from-transparent to-transparent',
  },
  amber: {
    ...DARK_NAVY,
    headerBg: 'from-transparent to-transparent',
    headerBorder: 'border-white/10',
    titleGradient: 'text-white',
    subtitleBg: 'bg-amber-500/15',
    subtitleText: 'text-amber-300',
    subtitleBorder: 'border-amber-500/25',
    overlay: 'from-transparent to-transparent',
  },
  sunset: {
    ...DARK_NAVY,
    indicator: 'bg-[#FF8A65]',
    iconActive: 'text-[#A33B32]',
    iconInactive: 'text-orange-100/80 group-hover:text-white',
    itemIdle: 'text-orange-50/90 hover:text-white hover:bg-white/[0.10]',
    itemActive: 'bg-white text-[#8F352F] shadow-lg shadow-[#3A1720]/25',
    groupActive: 'text-white bg-white/[0.10]',
    avatarGradient: 'from-[#FF8A65] to-[#D95045]',
    badge: 'bg-white/15 text-orange-50',
    headerBg: 'from-transparent to-transparent',
    headerBorder: 'border-white/15',
    titleGradient: 'text-white',
    subtitleBg: 'bg-white/10',
    subtitleText: 'text-orange-100/80',
    subtitleBorder: 'border-white/15',
    overlay: 'from-transparent to-transparent',
  },
  light: {
    brandGradient: 'from-orange-500 to-orange-600',
    brandShadow: 'shadow-orange-500/20',
    brandGlow: 'bg-orange-400/15',
    titleOrange: 'text-slate-900',
    titleGradient: 'text-slate-900',
    indicator: 'bg-orange-500',
    hideIndicator: true,
    iconActive: 'text-white',
    iconInactive: 'text-slate-400 group-hover:text-slate-600',
    itemIdle: 'text-slate-500 hover:text-slate-800 hover:bg-slate-100',
    itemActive: 'bg-orange-500 text-white shadow-md shadow-orange-500/20',
    groupActive: 'text-slate-900 bg-slate-100',
    groupIdle: 'text-slate-500 hover:text-slate-800 hover:bg-slate-100',
    avatarGradient: 'from-orange-500 to-orange-600',
    badge: 'bg-slate-100 text-slate-500',
    headerBg: 'from-transparent to-transparent',
    headerBorder: 'border-slate-100',
    subtitleBg: 'bg-slate-50',
    subtitleText: 'text-slate-400',
    subtitleBorder: 'border-slate-100',
    overlay: 'from-transparent to-transparent',
    searchFocus: 'focus:ring-orange-500/20 focus:border-orange-400/50',
    searchIconFocus: 'group-focus-within:text-slate-400',
  },
};

export function getSidebarAccent(key = 'brand') {
  return SIDEBAR_ACCENTS[key] || SIDEBAR_ACCENTS.brand;
}
