module.exports = {
  name: 'Him Journey Tours',
  brand: 'HIM JOURNEY TOURS',
  tagline: 'Explore · Experience · Memories',
  phone: process.env.COMPANY_PHONE || '+91 9317157005',
  email: process.env.SMTP_USER || 'bookinghimjourneytours@gmail.com',
  website: 'himjourneytours.in',
  websiteUrl: 'https://himjourneytours.in',
  address: 'Him Journey Tours, Chambaghat, Solan, Himachal Pradesh - 173213, India',
  instagram: 'https://www.instagram.com/him_journey_tours/',
  facebook: 'https://www.facebook.com/himjourneytours',
  gstin: process.env.COMPANY_GSTIN || '',
  pan: process.env.COMPANY_PAN || '',
  hsn: '998552',
  logoUrl: 'https://himjourneytours.in/wp-content/themes/odyssea/logo.jpg',
  bankName: 'HDFC BANK',
  accountName: 'Him Journey Tours',
  accountNo: '50200120620318',
  ifsc: 'HDFC0008311',
  bankBranch: 'SOLAN',
};
